[versions]
agp = "8.5.2"
coroutine = "1.9.0"
hilt = "2.52"
kotlin = "2.0.20"
lifecycle = "2.8.5"
lulkr = "0.0.2"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.9.2" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version = "2024.09.01" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-core = { group = "androidx.core", name = "core-ktx", version = "1.13.1" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.6.1" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version = "1.2.1" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version = "2.8.0" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.2.0" }
junit = { group = "junit", name = "junit", version = "4.13.2" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
kr-lul-logging = { module = "kr.lul:logging-kotlinmultiplatform", version.ref = "lulkr" }
kr-lul-semantic-version = { module = "kr.lul:semantic-version-kotlinmultiplatform", version.ref = "lulkr" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "2.0.20-1.0.24" }
modulegraph = { id = "dev.iurysouza.modulegraph", version = "0.10.1" }
